export const profile = {
  name: "Dhruv Solanki",
  role: "MERN Developer",
  tagline: "Entry-level engineer crafting clear, accessible web apps with React and Node",
  location: "Mumbai, India",
  email: "dhruvsolanki0129@gmail.com",
  socials: [
    { label: "LinkedIn", href: "https://www.linkedin.com/in/dhruv-solanki-699679313/" },
    { label: "X", href: "https://x.com/DhruvSolanki205" },
  ],
  platforms: [
    { label: "LeetCode", href: "https://leetcode.com/u/yyjfUbDoSh/" },
    { label: "GitHub", href: "https://github.com/DhruvSolanki01259" },
  ],
  about: [
    "I’m an aspiring Software Development Engineer with a strong foundation in Data Structures, Algorithms, and full‑stack web development using the MERN stack.",
    "I specialize in building scalable, secure, and user‑focused applications with technologies like React, Node.js, Express, and MongoDB. I’ve worked on projects involving secure authentication, responsive UIs, and RESTful APIs.",
    "I focus on writing clean, efficient, and maintainable code while ensuring a seamless user experience. I’m passionate about problem‑solving and basic system design, constantly exploring new technologies to stay future‑ready.",
    "My goal is to engineer impactful solutions that make technology simpler, faster, and more accessible for everyone.",
  ],
  education: [
    {
      degree: "Bachelor of Technology (B.Tech.)",
      institute: "K. J. Somaiya Institute of Technology",
      period: "2022 – 2026",
      field: "Computer Engineering",
      highlights: ["GPA: 8.3"],
    },
    {
      degree: "Higher Secondary Education (HSC)",
      institute: "Acharya Ambalal V. Patel Junior College",
      period: "2020 – 2022",
      highlights: ["Percentage: 60%"],
    },
    {
      degree: "Secondary Education (SSC)",
      institute: "St. Lawrence High School",
      period: "Till 2020",
      highlights: ["Percentage: 70%"],
    },
  ],
  skills: [
    "C",
    "C++",
    "HTML",
    "CSS",
    "JavaScript",
    "MongoDB",
    "Express.js",
    "React",
    "Node.js",
    "Tailwind CSS",
    "REST APIs",
    "Git & GitHub",
    "Basic System Design",
    "DSA",
  ],
  projects: [
    // {
    //   title: "DevNotes",
    //   description: "Full‑stack notes app with auth, tag search, and offline sync using React, Node, and MongoDB.",
    //   tags: ["React", "Node", "MongoDB", "TypeScript"],
    //   links: {
    //     live: "#",
    //     repo: "https://github.com/DhruvSolanki01259/devnotes",
    //   },
    //   imageAlt: "DevNotes app screenshot",
    //   image: "/notes-app-dashboard.jpg",
    // },
    // {
    //   title: "TaskFlow",
    //   description: "Kanban task manager with drag‑and‑drop, JWT auth, and REST API built on Express.",
    //   tags: ["React", "Express", "JWT", "Tailwind"],
    //   links: {
    //     live: "#",
    //     repo: "https://github.com/DhruvSolanki01259/taskflow",
    //   },
    //   imageAlt: "TaskFlow board screenshot",
    //   image: "/kanban-task-board.jpg",
    // },
    // {
    //   title: "ShopLite",
    //   description: "Minimal e‑commerce prototype with product listing, cart, and checkout flow.",
    //   tags: ["Next.js", "MongoDB", "Stripe (test)"],
    //   links: {
    //     live: "#",
    //     repo: "https://github.com/DhruvSolanki01259/shoplite",
    //   },
    //   imageAlt: "ShopLite product grid",
    //   image: "/ecommerce-product-grid.png",
    // },
    {
      title: "Sorting Visualizer",
      description: "Visual tool showcasing how different sorting algorithms work step by step.",
      tags: ["React", "Javascript", "Algorithms"],
      links: {
        live: "https://ds-sorting-visualizer-ds.vercel.app/",
        repo: "https://github.com/DhruvSolanki01259/Sorting-Visualizer",
      },
      imageAlt: "Sorting Visualizer",
      image: "/sorting-visualizer.png",
    },
    {
      title: "Auth Application",
      description: "Demonstrating a secure user authentication flow with email verification and password reset functionality.",
      tags: ["React", "Node", "Express", "MongoDB", "Resend"],
      links: {
        live: "https://auth-application-ds.vercel.app/",
        repo: "https://github.com/DhruvSolanki01259/Auth-Application",
      },
      imageAlt: "Auth Application",
      image: "/auth-application.png",
    },
  ],
} as const
